/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    public static void main(String[] args) {
        LinkedList myList = new LinkedList();
        myList.insert(5);
        myList.insert(10);
        myList.insert(15);

        System.out.println("LinkedList: " + myList.toString());
        System.out.println("Includes 10: " + myList.includes(10));
        System.out.println("Includes 20: " + myList.includes(20));
    }
}