/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;


import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static hashtable.HashMap.repeatedWord;
import static hashtable.LeftJoin.leftJoin;

public class App {

    public static void main(String[] args) {
       /* HashMap<String, Integer> hashMap = new HashMap<>(5);
        hashMap.set("one", 3);
        hashMap.set("two", 2);
        hashMap.set("three", 1);
        System.out.println("one= " + hashMap.get("one"));
        System.out.println("four= " + hashMap.has("four"));
        List<String> keys = hashMap.keys();
        System.out.println("Keys in HashMap: " + keys);
        hashMap.set("four", 4);
        System.out.println("four= " + hashMap.get("four"));
        keys = hashMap.keys();
        System.out.println("New keys in HashMap: " + keys);
        System.out.println("HashMap size: " + hashMap.size);
        String str = null;
        String repeated = repeatedWord(str);
        System.out.println("repeated word: " + repeated);

        str = "";
        repeated = repeatedWord(str);
        System.out.println("repeated word : " + repeated);

        str = "Once upon a time, there was a brave princess who...";
        repeated = repeatedWord(str);
        System.out.println("repeated word in '" + str + "': " + repeated);

        str = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        repeated = repeatedWord(str);
        System.out.println("Repeated word in '" + str + "': " + repeated);
*/

    }
}