/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Collection;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void setAndGetTest() {
        HashMap<String, Integer> hashMap = new HashMap<>(5);
        hashMap.set("one", 3);
        hashMap.set("two", 2);
        hashMap.set("three", 1);
        assertEquals(3, (int) hashMap.get("one"));
        assertEquals(2, (int) hashMap.get("two"));
        assertEquals(1, (int) hashMap.get("three"));
        hashMap.set("one", 5);
        assertEquals(5, (int) hashMap.get("one"));
    }

    @Test
    void nullTest() {
        HashMap<String, Integer> hashMap = new HashMap<>(5);
        assertNull(hashMap.get("four"));
    }

    @Test
    void keysTest() {
        HashMap<String, Integer> hashMap = new HashMap<>(5);
        hashMap.set("one", 3);
        hashMap.set("two", 2);
        hashMap.set("three", 1);
        Collection<String> keys = hashMap.keys();
        assertTrue(keys.contains("one"));
        assertTrue(keys.contains("two"));
        assertTrue(keys.contains("three"));
        hashMap.set("four", 4);
        keys = hashMap.keys();
        assertTrue(keys.contains("four"));
    }

    @Test
    void collisionTest() {
        HashMap<String, Integer> hashMap = new HashMap<>(1);
        hashMap.set("one", 5);
        hashMap.set("two", 10);
        assertEquals(5, (int) hashMap.get("one"));
        assertEquals(10, (int) hashMap.get("two"));
    }

    @Test
    void hashTest() {
        HashMap<String, Integer> hashMap = new HashMap<>(5);
        int hashValue = hashMap.hash("one");
        assertTrue(hashValue >= 0 && hashValue < 5);
    }
    @Test
    void repeatedWordTest() {
        String str = "Once upon a time, there was a brave princess who...";
        String result = HashMap.repeatedWord(str);
        assertEquals("a", result);

        str = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        result = HashMap.repeatedWord(str);
        assertEquals("summer", result);

    }

}