/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayinsertshift;
import java.util.Arrays;
public class Library {
    public static int[] insertShiftArray(int[] arr, int val) {
        int[] newArr = new int[arr.length + 1];
        int midIndex = (newArr.length - 1) / 2;

        for (int i = 0; i < newArr.length; i++) {
            if (i < midIndex) {
                newArr[i] = arr[i];
            } else if (i == midIndex) {
                newArr[i] = val;
            } else {
                newArr[i] = arr[i - 1];
            }
        }
        System.out.println(Arrays.toString(newArr));
        return newArr;
    }
}