/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arraybs;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void BinarySearchTest() {
        Library sut = new Library();
        int[] arr = {1, 3, 5, 7, 9, 11};
        int key = 7;
        int expectedIndex = 3;
        int actualIndex = sut.BinarySearch(arr, key);
        Assertions.assertEquals(expectedIndex, actualIndex);
        System.out.println(actualIndex);
        key = 12;
        expectedIndex = -1;
        actualIndex = sut.BinarySearch(arr, key);
        Assertions.assertEquals(expectedIndex, actualIndex);
        System.out.println(actualIndex);

    }
}
